# 3.0 Introduction to Numpy 

Numpy is a very important Python package and is used for many applications in science. Numpy offers mathematical functions, linear algebra and much more. Most usefully, it is a package to do vectorized array programming. It is probably one of the most widely used packages in python and underpins other important libraries such as Pandas (data science) matplotlib (plotting) and scikit-image (image processing).

We will do a whistle stop tour of Numpy today to show you some concepts of array programming. It is worth delving into this pacakge a bit more to understand what is gonig on. You can find the documentation for Numpy at https://numpy.org/doc/stable/user/absolute_beginners.html

## 3.1 Importing Numpy

During the course you will have seen the `import` statement at the top of some cells and may wonder what this is doing. Remember namespaces from earlier in the course? All the `import` statement is doing is bringing packages into the global namespace. You will often see the import of Numpy written as it is is in the cell below , we abbreviate `numpy` to `np` so we have less to type. We can access objects from the numpy package using the `.` notation. In the cell below we are importing Numpy and accessing the value of `pi` using the `.` notation. 




In [3]:
import numpy as np

print(np.pi)

3.141592653589793


## 3.2 The Numpy Array
### 3.2.1 Creating an array

[ref: https://numpy.org/doc/stable/user/absolute_beginners.html ]
An array is a central data structure of the NumPy library. An array is a grid of values and it contains information about the raw data, how to locate an element, and how to interpret an element. It has a grid of elements that can be indexed in various ways. The elements are all of the same type, referred to as the array dtype.

Run the example code below to generate arrays of different shapes and sizes:


In [4]:
x = np.array([1,2,3,4])
print('1-D array: ', x)

y = np.array([[1,0,0],[0,1,0], [0,0,1]])
print('2-D  array:', y )

z = np.zeros([2,2,2])
print('3D array of zeros:', z)

1-D array:  [1 2 3 4]
2-D  array: [[1 0 0]
 [0 1 0]
 [0 0 1]]
3D array of zeros: [[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


We can also create non-numeric arrays, but unlike lists arrays must contain data of the same `type`. Run the example code below that creates a list and then uses the `np.array` function to turn it into an array. What happens when you run the code? What has numpy done automatically in this example?

In [5]:
my_list = ['red', 'yellow', 1, 'purple']

print(my_list)

my_arr = np.array(my_list)
print(my_arr)

['red', 'yellow', 1, 'purple']
['red' 'yellow' '1' 'purple']


### 3.2.2 Indexes and slicing
One advantage of using arrays is they can be indexed. This means you can select elements and slices of an array. You can do this is several different ways demonstrated in the cell below. It is important to note that Python indexes from 0 . Other languages such as Matlab and R index from 1. 

In [6]:
# Indexing with a non-negative integer
print("First Element in x=[1,2,3,4]:")
print(x[0])

print(" Middle line of [[1 0 0], [0 1 0], [0 0 1]]:")
print(y[:,1]) 

print("Second face of a 3D array:")
print([z[:,:, 1]]) 

print("First element of  2-D array:")
print(y[0,0]) 

print("First 2 elements of the first column in a 2-D array:")
print(y[0,:2])

First Element in x=[1,2,3,4]:
1
 Middle line of [[1 0 0], [0 1 0], [0 0 1]]:
[0 1 0]
Second face of a 3D array:
[array([[0., 0.],
       [0., 0.]])]
First element of  2-D array:
1
First 2 elements of the first column in a 2-D array:
[1 0]


### 3.2.3 Shape and Dimensions

You can find the size and the dimensions of any array with a couple of very useful functions from the Numpy package `np.shape` and `np.ndim`.

`np.shape` gives you the size of each of the dimensions of the array.
`n.ndim` gives you the number of dimensions the array has. 
Run the cell below to see an example:

In [18]:
print("Shape of x:")
print(np.shape(x))
print("Number of dimensions of x:")
print(np.ndim(x))

print("Shape of y:")
print(np.shape(y))
print("Number of dimensions of y:")
print(np.ndim(y))

print("Shape of z:")
print(np.shape(z))
print("Number of dimensions of z:")
print(np.ndim(z))

Shape of x:
(4,)
Number of dimensions of x:
1
Shape of y:
(3, 3)
Number of dimensions of y:
2
Shape of z:
(2, 2, 2)
Number of dimensions of z:
3


As you can see from the above example array indexing and slicing is very powerful and flexible. You can even use other arrays to select out indicies.

### Exercises

* Make your own 2-D numpy array of any type
* Select the 2 element of your array
* Select the 1st column of your array

In [7]:
# Your examples here

## 3.3 Array Operations
### 3.3.1 Simple Operations

The operators that we learnt in the last notebook (e.g. `+,/,*,-`) work element wise on numpy arrays. Run the cell below for some examples: 

In [8]:
arr = np.array([1,2,3,4])

print("add 1:")
print(arr + 1)

print("Make negative:")
print(arr*-1)

print("divide by 100")
print(arr/100)


add 1:
[2 3 4 5]
Make negative:
[-1 -2 -3 -4]
divide by 100
[0.01 0.02 0.03 0.04]


These are examples of *vectorized* operations. This gives an increase in performance over using things like loops. For example if you want to square every number in a list, you would have to run a `for` loop executing multiply by two on each element on the list. For a numpy array you simply square the whole array. 

Run the cell below to see the difference in the time it takes to run a loop versus a vectorized operation.

In [15]:
from time import time

my_list = list(range(1,100000)) # generate a list of numbers 1 to 100,000
arr = np.array(range(1,100000)) # generate an array of numbers 1 to 100,000

t_start= time()
output = []
for item in my_list:
    output.append(item**2)
    
t_end = time()
print("time to run multiplication as loop: ",  t_end-t_start)


t_start= time()
arr**2    
t_end = time() 
print("time to run multiplication as loop: ",  t_end-t_start)


time to run multiplication as loop:  0.03128957748413086
time to run multiplication as loop:  0.0


### 3.3.2 Opertions between Numpy arrays

Here we have just done simple operations on numpy arrays but of course you can do operations between numpy arrays.
Run the cell below to see what happens when you perform different operations on arrays.


In [10]:
a = np.array([1, 2, 3])
b = np.array([1, 2, 3])
c = np.array([[1, 2, 3],[4,5,6], [7,8,9]])
d = np.array([[1],[2],[3]]),
print(a + b)
print(a * b)

print( a + c)
print( a * c)

print(c + d)
print(c * d)

[2 4 6]
[1 4 9]
[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]
[[ 1  4  9]
 [ 4 10 18]
 [ 7 16 27]]
[[[ 2  3  4]
  [ 6  7  8]
  [10 11 12]]]
[[[ 1  2  3]
  [ 8 10 12]
  [21 24 27]]]


  As you can see from the example above operations run elementwise when we have arrays of the same dimesions. Where we have array `a`,  dimensions 1 x 3, and array `c` dimensions of 3x3 , the operations work elementwise along the rows. When we look at operations between the array `d`, dimensions 3x1 and `c` we can see the operations work elementwise along the columns.  
  
When you want to operations on two arrays you need to make sure that their shapes can be broadcast. This means that at least one dimension must fit completely into the other. If not Numpy will throw an error as it does not know how to apply the elementwise operation. Run the cell below to see this in action:

In [14]:
a = np.array([[1,0],[0,1]])
b= np.array([[1,2,3,4],[5,6,7,8],[1,2,3,4],[5,6,7,8]])

print(a * b)

ValueError: operands could not be broadcast together with shapes (2,2) (4,4) 

## 3.4 Functions and Plotting

Numpy is not just about arrays, there are many useful mathematical functions that are part of Numpy. In this example we will focus on the triganomic functions to get a feel for how to work with Numpy and its power when processing this. It is important to note here that most things are written for you , you probably won't have to write things from scratch.

### 3.4.1 The trigonometric functions

The trignometric functions are represented in numpy as the following: `np.sin`, `np.cos`, `np.tan`. The hyperbolic functions being represented as `np.sinh`, `np.cosh`, `np.tanh`. 

These functions are calculated in radians so `np.deg2rad` , `np.radians` and `np.degrees` are all very useful functions to go with them. See we told you, you wouldn't need to write anything from scratch!

Run the cell below to see the functions doing some basic calculations:


In [22]:
print("Sin 30 degrees")
print(np.sin(np.deg2rad(30)))

print("Cos 0 degrees")
print(np.cos(0))

print("Tan pi/4 radians")
print(np.tan(np.pi/4))

Sin 30 degrees
0.49999999999999994
Cos 0 degrees
1.0
Tan pi/2 radians
0.9999999999999999


### 3.4.2 